nimble:
  server:
    port: 7922

  spring:
    application:
      name: provider

    datasource:
      platform: mysql
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/nimble?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: admin
      password: admin
      root:
      schema: classpath:database/schema.sql
      data: classpath:database/data.sql

#    h2:
#      console:
#        enabled: true
#        path: '/h2'
#        settings:
#          web-allow-others: true

    jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5Dialect
      generate-ddl: false
      show-sql: true
      hibernate:
#        ddl-auto: update
        ddl-auto: none

  eureka:
    client:
      service-url:
        defaultZone: http://eureka1:7901/eureka,http://eureka2:7902/eureka
    instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${server.port}

  logging:
    level:
      root: info
      org.hibernate: info
      org.hibernate.type.descriptor.sql.BasicBinder: trace
      org.hibernate.type.descriptor.sql.BasicExtractor: trace
#    com.xxxx.xxxx: DEBUG
